## AND 게이트 (no activation)

In [1]:
def AND(x1, x2):
    w1, w2, bias = 0.5, 0.5, 0.7
    #가중치, bias 0과 1 사이의 값으로 지정
    temp = x1 * w1 + x2 * w2
    if temp <= bias:
        return 0
    else:
        return 1

In [2]:
AND(0,0)

0

In [3]:
AND(1,0)

0

In [4]:
AND(0,1)

0

In [5]:
AND(1,1)

1

## NAND 게이트 (no activation)

In [6]:
import numpy as np

def NAND(x1, x2):
    x = np.array([x1, x2]) #numpy array에 배치
    w = np.array([-.5, -.5])
    b = 0.7
    temp = np.sum(x * w) + b
    if temp <= 0:
        return 0
    else:
        return 1

In [7]:
NAND(0,0)

1

In [8]:
NAND(0,1)

1

In [9]:
NAND(1,0)

1

In [10]:
NAND(1,1)

0

## OR 게이트 (no activation)

In [11]:
def OR(x1, x2):
    x = np.array([x1, x2])
    w = np.array([.5, .5])
    b = -.2
    temp = np.sum(x * w) + b
    if temp <= 0:
        return 0
    else:
        return 1

## XOR 게이트 (no activation)

In [12]:
def XOR(x1, x2):
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    y = AND(s1, s2)
    return y

In [13]:
XOR(0,0)

0

In [14]:
XOR(1,0)

1

In [15]:
XOR(0,1)

1

In [16]:
XOR(1,1)

0

## Activation Function (활성화 함수)
#### 1. step function

In [17]:
def step_function(x):
    if x > 0:
        return 1
    else:
        return 0

In [18]:
x = 2.1
step_function(x)

1

In [22]:
def step_function(x):
    y = x > 0 #y:BOOLtype (True, False)
    return y.astype(np.int)

In [23]:
x = np.array([-1., 1., 2.])
step_function(x)

#step_function을 재정의해주면 numpy array 형태에도 적용가능

array([0, 1, 1])

#### 2. Sigmoid

In [24]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [25]:
sigmoid(x)

array([0.26894142, 0.73105858, 0.88079708])

#### 3. ReLU

In [26]:
def ReLU(x):
    return np.maximum(0,x)

In [27]:
ReLU(x)

array([0., 1., 2.])

#### 4. Softmax

In [28]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [29]:
a = np.array([1, 2, 3])
softmax(a)

array([0.09003057, 0.24472847, 0.66524096])

In [30]:
a = np.array([710, 800, 2010, 400, 500, 902, 703])
softmax(a)
#숫자가 너무 커지면 계산이 불가능해짐, softmax 함수를 재정의해줘야함

<ipython-input-28-37433be62e67>:2: RuntimeWarning: overflow encountered in exp
  exp_a = np.exp(a)
<ipython-input-28-37433be62e67>:4: RuntimeWarning: invalid value encountered in true_divide
  y = exp_a / sum_exp_a


array([nan, nan, nan,  0.,  0., nan,  0.])

In [31]:
def softmax(a):
    c = np.max(a) #최댓값 빼주는 normalization 작업
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [32]:
a = np.array([710, 800, 2010, 400, 500, 902, 703])
softmax(a)

array([0., 0., 1., 0., 0., 0., 0.])

## Neural Network

In [36]:
#input으로 2개를 지정해줄 것이기 때문에 2*3의 neural network 필요함

def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]]) #weight(가중치)
    network['b1'] = np.array([0.1, 0.2, 0.3]) #bias(편향)
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    return network

In [39]:
#Neural Network 짜보기

#feed-forward: input값 ▶ 결과값
#back-propagation: 결과값 ▶ input값 (지정한 weight, bias이 맞지 않는다면 수정하기 위함)
def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = softmax(a3)
    
    return y

In [41]:
network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
y

#확률값으로 출력, 2개의 값 더하면 1

array([0.40625907, 0.59374093])