<a href="https://colab.research.google.com/github/kizoey/KUCC_NLP_DL_Session/blob/main/Week01.%20%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. 산술연산**

In [ ]:
1 - 2

-1

In [ ]:
4 * 5

20

In [ ]:
7 / 5

1.4

In [ ]:
3 ** 2

9

# **2. 자료형**

In [ ]:
type(10)

int

In [ ]:
type(2.718)

float

In [ ]:
type("hello")

str

# **3. 변수**

In [ ]:
x = 10
print(x)

10


In [ ]:
x = 100
print(x)

100


In [ ]:
y = 3.14
x * y

314.0

In [ ]:
type(x * y)

float

# **4. 리스트**

In [ ]:
a = [1, 2, 3, 4, 5]
print(a)

[1, 2, 3, 4, 5]


In [ ]:
len(a)

5

In [ ]:
a[0]

1

In [ ]:
a[4]

5

In [ ]:
a[4] = 99
print(a)

[1, 2, 3, 4, 99]


In [ ]:
a[1:3]

[2, 3]

In [ ]:
a[1:]

[2, 3, 4, 99]

In [ ]:
a[:3]

[1, 2, 3]

In [ ]:
a[:-1]

[1, 2, 3, 4]

In [ ]:
a[:-2]

[1, 2, 3]

# **5. 딕셔너리**

In [ ]:
me = {'height':180}
me['height']

180

In [ ]:
me['weight'] = 70
print(me)

{'height': 180, 'weight': 70}


# 6. **Bool**

In [ ]:
hungry = True
sleepy = False
type(hungry)

bool

In [ ]:
not hungry

False

In [ ]:
hungry and sleepy

False

In [ ]:
hungry or sleepy

True

# 7. **if문**

In [ ]:
hungry = True
if hungry:
  print("I'm hungry")

I'm hungry


In [ ]:
hungry = False
if hungry:
  print("I'm hungry")
else:
  print("I'm not hungry")

I'm not hungry


# 8. **For문**

In [ ]:
for i in [1, 2, 3]:
  print(i)

1
2
3


# 9. **함수**

In [ ]:
def hello():
  print("Hello World!")

hello()

Hello World!


In [ ]:
def hello(object):
  print("Hello" + object + "!")

hello("cat")

Hellocat!


# 10. **클래스**

In [ ]:
class Man:
  def __init__(self, name):
    self.name = name
    print("Initialized!")

  def hello(self):
    print("Hello " + self.name + "!")

  def goodbye(self):
    print("Good-bye " + self.name + "!")

m = Man("David")
m.hello()
m.goodbye()

Initialized!
Hello David!
Good-bye David!


# **11. Numpy**

In [ ]:
import numpy as np

In [ ]:
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

# 12. **N차원 배열**

In [ ]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [ ]:
print(A.shape)

(2, 2)


In [ ]:
print(A.dtype)

int64


# **13. 산술 연산**

In [ ]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x + y)
print(x - y)
print(x * y)
print(x / y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [ ]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0

array([0.5, 1. , 1.5])

# **14. 원소 접근**

In [ ]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [ ]:
X[0]

array([51, 55])

In [ ]:
X[0][1]

55

In [ ]:
for row in X:
  print(row)

[51 55]
[14 19]
[0 4]


# **15. 평탄화**

In [ ]:
X = X.flatten()
print(X)
X[np.array([0, 2, 4])]

[51 55 14 19  0  4]


array([51, 14,  0])